# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Machine Learning for Agriculture and Natural Systems
description:      'How to manage and manipulate data for agricultural research'
url:              http://okstate-wade.github.io/MLAgNR
baseurl:          /MLAgNR
email:            jeff.sadler@okstate.edu

author:
  name:           'Jeff Sadler'
  url:            http://pss.okstate.edu/People/faculty-1/faculty-info/alderman-phillip/phillip-alderman

github:
  repo:           https://okstate-wade.github.io/MLAgNR
  #               Be sure the 'Issues' feature is activated in 'Settings'
