# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction to Scientific Computing
description:      'Teaching your computer to do work for you'
url:              http://palderman.github.io/IntroSciComp
baseurl:          /IntroSciComp
email:            phillip.alderman@okstate.edu

author:
  name:           'Phillip Alderman'
  url:            http://pss.okstate.edu/People/faculty-1/faculty-info/alderman-phillip/phillip-alderman

github:
  repo:           https://github.com/palderman/IntroSciComp
  #               Be sure the 'Issues' feature is activated in 'Settings'
